// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8-lT94mCs28uSG-tdz3V6Ph-AS5A_0_A',
    appId: '1:670192463218:web:375749a18d82872a4341eb',
    messagingSenderId: '670192463218',
    projectId: 'lab12-3554f',
    authDomain: 'lab12-3554f.firebaseapp.com',
    storageBucket: 'lab12-3554f.appspot.com',
    measurementId: 'G-WF463NSCMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7UoR_RIqk48P3plNAEO7qCP4gD1NsiyU',
    appId: '1:670192463218:android:772d53c08add18f94341eb',
    messagingSenderId: '670192463218',
    projectId: 'lab12-3554f',
    storageBucket: 'lab12-3554f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJxHqk7strJW1MzY_wwWEQqG9uDdv1w6A',
    appId: '1:670192463218:ios:8de049331a5a1bb74341eb',
    messagingSenderId: '670192463218',
    projectId: 'lab12-3554f',
    storageBucket: 'lab12-3554f.appspot.com',
    iosBundleId: 'com.example.lab12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJxHqk7strJW1MzY_wwWEQqG9uDdv1w6A',
    appId: '1:670192463218:ios:4bdf262c36a803c54341eb',
    messagingSenderId: '670192463218',
    projectId: 'lab12-3554f',
    storageBucket: 'lab12-3554f.appspot.com',
    iosBundleId: 'com.example.lab12.RunnerTests',
  );
}
